# -*- coding: utf-8 -*-
"""california

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/165ryjv-3a-EYy5ElBVmuKF6CRoIaAmFH
"""

import pandas as pd

df=pd.read_csv('/content/california_housing_test.csv')

display(df.head())

display(df.describe())

display(df.columns)

display(df.isnull().sum())

import matplotlib.pyplot as plt

numerical_cols = ['longitude', 'latitude', 'households', 'population']

fig, axes = plt.subplots(nrows=len(numerical_cols), ncols=1, figsize=(8, 6 * len(numerical_cols)))
for i, col in enumerate(numerical_cols):
    axes[i].boxplot(df[col], vert=False)
    axes[i].set_title(f'Box plot of {col}')
    axes[i].set_xlabel(col)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

numerical_cols = ['longitude', 'latitude', 'households', 'population']

fig, axes = plt.subplots(nrows=len(numerical_cols), ncols=1, figsize=(8, 6 * len(numerical_cols)))
for i, col in enumerate(numerical_cols):
    axes[i].hist(df[col], bins=20)
    axes[i].set_title(f'Distribution of {col}')
    axes[i].set_xlabel(col)
    axes[i].set_ylabel('Frequency')
plt.tight_layout()
plt.show()