# -*- coding: utf-8 -*-
"""netflix

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10R3bO0I2vKpnSo4XuOPh9rTeTTBo_0tH
"""

pip install packages

import pandas as pd

df=pd.read_csv('/content/netflix_titles.csv')

display(df.head())

display(df.describe())

display(df.columns)

display(df.isnull().sum())

import matplotlib.pyplot as plt

# Select categorical columns for bar plots
categorical_cols = ['country', 'type', 'director']

fig, axes = plt.subplots(nrows=len(categorical_cols), ncols=1, figsize=(8, 6 * len(categorical_cols)))

for i, col in enumerate(categorical_cols):
    # Convert column to string type to handle potential non-string values
    df[col] = df[col].astype(str)
    # Get value counts for each category
    value_counts = df[col].value_counts()

    # For columns with many unique values, show only the top 10
    if col in ['country', 'director'] and len(value_counts) > 10:
        value_counts = value_counts.head(10)

    # Plot bar chart of value counts
    axes[i].bar(value_counts.index, value_counts.values)
    axes[i].set_title(f'Distribution of {col}')
    axes[i].set_xlabel(col)
    axes[i].set_ylabel('Frequency')
    # Rotate x-axis labels for better readability if there are many categories
    if len(value_counts.index) > 5: # Adjust rotation threshold based on top N displayed
        axes[i].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()